"""Tests for the auto-generated docs functionality."""

from __future__ import annotations

import pytest

from nexus_router.docs import (
    AdapterEntry,
    DocsGenerationResult,
    KNOWN_ADAPTERS,
    generate_adapter_docs,
)
from nexus_router.tool import generate_adapter_docs as generate_docs_tool


class TestAdapterEntry:
    """Test AdapterEntry dataclass."""

    def test_adapter_entry_minimal(self) -> None:
        """AdapterEntry works with minimal args."""
        entry = AdapterEntry(
            factory_ref="pkg:create_adapter",
            package_name="pkg",
        )
        assert entry.factory_ref == "pkg:create_adapter"
        assert entry.package_name == "pkg"
        assert entry.repo_url is None
        assert entry.config is None

    def test_adapter_entry_full(self) -> None:
        """AdapterEntry works with all args."""
        entry = AdapterEntry(
            factory_ref="pkg:create_adapter",
            package_name="pkg",
            repo_url="https://github.com/org/pkg",
            config={"key": "value"},
        )
        assert entry.repo_url == "https://github.com/org/pkg"
        assert entry.config == {"key": "value"}


class TestKnownAdapters:
    """Test KNOWN_ADAPTERS registry."""

    def test_known_adapters_not_empty(self) -> None:
        """KNOWN_ADAPTERS contains at least one adapter."""
        assert len(KNOWN_ADAPTERS) > 0

    def test_known_adapters_http(self) -> None:
        """HTTP adapter is in KNOWN_ADAPTERS."""
        http_entries = [e for e in KNOWN_ADAPTERS if "http" in e.package_name]
        assert len(http_entries) == 1
        assert http_entries[0].factory_ref == "nexus_router_adapter_http:create_adapter"


class TestGenerateAdapterDocs:
    """Test generate_adapter_docs() function."""

    def test_generate_docs_default(self) -> None:
        """generate_adapter_docs() works with defaults."""
        result = generate_adapter_docs()

        assert isinstance(result, DocsGenerationResult)
        assert result.adapters_ok >= 1
        assert result.adapters_failed == 0
        assert len(result.errors) == 0
        assert len(result.markdown) > 0

    def test_generate_docs_contains_header(self) -> None:
        """Generated docs include header."""
        result = generate_adapter_docs()

        assert "AUTO-GENERATED FILE" in result.markdown
        assert "Official Adapters" in result.markdown

    def test_generate_docs_contains_summary(self) -> None:
        """Generated docs include summary table."""
        result = generate_adapter_docs()

        assert "## Summary" in result.markdown
        assert "| Adapter | Kind |" in result.markdown

    def test_generate_docs_contains_http_adapter(self) -> None:
        """Generated docs include HTTP adapter section."""
        result = generate_adapter_docs()

        assert "### http adapter" in result.markdown
        assert "`nexus-router-adapter-http`" in result.markdown
        assert "base_url" in result.markdown
        assert "TIMEOUT" in result.markdown

    def test_generate_docs_contains_config_table(self) -> None:
        """Generated docs include config parameter table."""
        result = generate_adapter_docs()

        assert "| Parameter | Type | Required |" in result.markdown
        assert "`base_url`" in result.markdown

    def test_generate_docs_custom_title(self) -> None:
        """generate_adapter_docs() accepts custom title."""
        result = generate_adapter_docs(title="My Custom Adapters")

        assert "# My Custom Adapters" in result.markdown

    def test_generate_docs_no_header(self) -> None:
        """generate_adapter_docs() can omit header."""
        result = generate_adapter_docs(include_header=False)

        assert "AUTO-GENERATED FILE" not in result.markdown

    def test_generate_docs_no_footer(self) -> None:
        """generate_adapter_docs() can omit footer."""
        result = generate_adapter_docs(include_footer=False)

        assert "Generated by nexus-router" not in result.markdown

    def test_generate_docs_custom_adapters(self) -> None:
        """generate_adapter_docs() accepts custom adapter list."""
        # Use the HTTP adapter since it's installed
        custom_adapters = [
            AdapterEntry(
                factory_ref="nexus_router_adapter_http:create_adapter",
                package_name="custom-http",
                config={"base_url": "https://custom.example.com"},
            ),
        ]

        result = generate_adapter_docs(adapters=custom_adapters)

        assert result.adapters_ok == 1
        assert "custom-http" in result.markdown

    def test_generate_docs_failed_adapter(self) -> None:
        """generate_adapter_docs() handles failed adapters."""
        bad_adapters = [
            AdapterEntry(
                factory_ref="nonexistent_pkg:create_adapter",
                package_name="bad-adapter",
            ),
        ]

        result = generate_adapter_docs(adapters=bad_adapters)

        assert result.adapters_ok == 0
        assert result.adapters_failed == 1
        assert len(result.errors) == 1


class TestDocsGenerationResult:
    """Test DocsGenerationResult dataclass."""

    def test_to_dict(self) -> None:
        """to_dict() returns expected structure."""
        result = generate_adapter_docs()
        d = result.to_dict()

        assert "markdown" in d
        assert "adapters_ok" in d
        assert "adapters_failed" in d
        assert "errors" in d
        assert isinstance(d["markdown"], str)
        assert isinstance(d["adapters_ok"], int)


class TestGenerateDocsToolApi:
    """Test tool.generate_adapter_docs() public API."""

    def test_tool_api_default(self) -> None:
        """tool.generate_adapter_docs() works with no args."""
        response = generate_docs_tool()

        assert response["adapters_ok"] >= 1
        assert response["adapters_failed"] == 0
        assert "markdown" in response

    def test_tool_api_with_request(self) -> None:
        """tool.generate_adapter_docs() accepts request dict."""
        response = generate_docs_tool({
            "title": "Test Adapters",
            "include_footer": False,
        })

        assert "# Test Adapters" in response["markdown"]
        assert "Generated by nexus-router" not in response["markdown"]
